version: '3'
services:

  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - wpsite
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress/
    image: wordpress
    volumes:
      - www-data:/var/www/html/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - wpsite
    restart: always
    env_file:
      - .env

  nginx:
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - www-data:/var/www/html/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - wpsite
    restart: always
    env_file:
      - .env

  ftps:
    build: requirements/bonus/ftps/
    image: ftps
    container_name: ftps
    volumes:
      - www-data:/home/mbari
    ports:
      - "21:21"
      - "21000:21000"
    networks:
      - wpsite
    restart: always
    env_file:
      - .env

  adminer:
    build: requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    ports:
      - 7077:7077
    depends_on:
      - nginx
    networks:
      - wpsite
    restart: always

  redis:
    build: requirements/bonus/redis/
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    depends_on:
      - nginx
    networks:
      - wpsite
    restart: always
    env_file:
      - .env

  backup:
    container_name: backup
    build: requirements/bonus/backup/
    image: backup
    networks:
      - wpsite
    depends_on:
      - mariadb
    volumes:
      - db-data:/db-data
      - backup-data:/backup
    restart: always
    env_file:
      - .env

  website:
    container_name: website
    build: requirements/bonus/website/
    image: website
    networks:
      - wpsite
    ports:
      - "7777:7777"
    restart: always
    env_file:
      - .env

networks:
  wpsite:
    driver: bridge

volumes:
  db-data:
    driver_opts:
      type: none
      device: /home/mbari/data/db-data
      o: bind
  www-data:
    driver_opts:
      type: none
      device: /home/mbari/data/www-data
      o: bind
  backup-data:
    driver_opts:
      type: none
      device: /home/mbari/data/backup-data
      o: bind
